kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: webapp
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      nodePort: 30080
  selector:
    app: webapp

  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-queue
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  selector:
    app: queue

  type: NodePort