apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: fleetman-webapp
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: fleetman-queue
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      name: queue
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: position-simulator
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      name: position-simulator
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice